#!/bin/sh

. ../support/simple_eval_tools.sh

HEADER Agent uses specified source for trapsink

SKIPIF NETSNMP_DISABLE_SNMPV2C

# We need to set $SNMP_TEST_DEST to a real IP address; we have a helper script
# to determine this
MYIP=`perl ./Smyip`
if [ $? -ne 0 ]
then
    SKIP "can not determine my IP"
fi

SNMP_TEST_DEST=${MYIP}:

# Standard V2c configuration
. ./Sv2cconfig

#XXXX
AGENT_FLAGS="$AGENT_FLAGS -DALL"

CONFIGAGENT trap2sink -s 127.0.0.1 ${SNMP_TRANSPORT_SPEC}:${SNMP_TEST_DEST}${SNMP_SNMPTRAPD_PORT} public
CONFIGTRAPD authcommunity log public
CONFIGTRAPD agentxsocket /dev/null

STARTTRAPD

STARTAGENT

# We just rely on the coldstart trap, so there is no active test here.

STOPAGENT

STOPTRAPD

# Check that the coldstart trap packet was sourced from localhost
CHECKTRAPDCOUNT atleastone "UDP: \[127\.0\.0\.1\]:[0-9]*->"

FINISHED
