language: c
compiler:
 - clang
 - gcc
env:
 - EXTRA_CONFIG=""
 - EXTRA_CONFIG='--with-security-modules=tsm --with-transports="DTLSUDP TLSTCP"'
script: ./configure --with-defaults --enable-ipv6 --enable-silent-libtool --disable-embedded-perl \$EXTRA_CONFIG && make && cd testing && ./RUNFULLTESTS -g all
# We need libperl-dev to build with perl
# and libpython-dev to build with python
# For now we don't attempt to require specific versions.
# (I think we could use a matrix to install different
# versions of perl and python for testing)
# also need openssl for TLS support
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libperl-dev python2.7-dev libssl-dev
